
def getWeatherType(val):
  if(val=="Thunderstorm"):return(1) 
  if(val=="Drizzle"):return(2)
  if(val=="Rain"):return(3)
  if(val=="Snow"):return(4) 
  if(val=="Mist"):return(5) 
  if(val=="Smoke"):return(6)
  if(val=="Dust"):return(7)
  if(val=="Fog"):return(8)
  if(val=="Haze"):return(9)
  if(val=="Sand"):return(10)
  if(val=="Ash"):return(11)
  if(val=="Squall"):return(12)
  if(val=="Tornado"):return(13)
  if(val=="Clear"):return(14)
  if(val=="Clouds"):return(15)
  else: return 0 #never will happen unless an error has occurred

def getWeatherCode(val):
  if(val==1): return("Thunderstorm")
  if(val==2): return("Drizzle")
  if(val==3): return("Rain")
  if(val==4): return("Snow")
  if(val==5): return("Mist")
  if(val==6): return("Smoke")
  if(val==7): return("Dust")
  if(val==8): return("Fog")
  if(val==9): return("Haze")
  if(val==10): return("Sand")
  if(val==11): return("Ash")
  if(val==12): return("Squall")
  if(val==13): return("Tornado")
  if(val==14): return("Clear")
  if(val==15): return("Clouds")
  else: return("Null")